sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t fdubuisson/telegraf-rpi .
# test image
- docker run fdubuisson/telegraf-rpi telegraf version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(docker run fdubuisson/telegraf-rpi telegraf version | cut -d ' ' -f 2)
    docker tag fdubuisson/telegraf-rpi fdubuisson/telegraf-rpi:$TAG
    docker push fdubuisson/telegraf-rpi:$TAG
    docker push fdubuisson/telegraf-rpi
  fi
